base_url: https://dcp2.jboss.org/v2/rest/search/developer_materials?
content:
  - jbossdeveloper_quickstart
  - jbossdeveloper_demo
  - jbossdeveloper_bom
  - jbossdeveloper_archetype
  - jbossdeveloper_example
  - jbossdeveloper_vimeo
  - jbossdeveloper_youtube
  - jbossdeveloper_book
  - jbossdeveloper_event
  - jbossdeveloper_cheatsheet
  - rht_website
