content:
  - jbossdeveloper_quickstart
  - jbossdeveloper_demo
  - jbossdeveloper_example
  - jbossdeveloper_vimeo
  - jbossdeveloper_youtube
  - jbossdeveloper_book
  - jbossdeveloper_event
  - jbossdeveloper_cheatsheet
  - rht_website
